import styles from "./technology-chips.module.css";

const TECHNOLOGY_ICONS: Record<string, string> = {
  "C++": "cplusplus",
  "Electron": "electron",
  "React": "react",
  "React 19": "react",
  "React Native": "react",
  "Supabase": "supabase",
  "Supabase Auth": "supabase",
  "Supabase Edge Functions": "supabase",
  "Next.js": "nextdotjs",
  "Next.js 16": "nextdotjs",
  "Swift": "swift",
  "Kotlin": "kotlin",
  "Tailwind": "tailwindcss",
  "Tailwind v4": "tailwindcss",
  "Tailwind CSS": "tailwindcss",
  "Tailwind CSS v4": "tailwindcss",
  "Node": "nodedotjs",
  "Node.js": "nodedotjs",
  "PostgreSQL": "postgresql",
  "Postgres": "postgresql",
  "pgvector": "postgresql",
  "Python": "python",
  "Apple": "apple",
  "iOS": "apple",
  "macOS": "apple",
  "SwiftUI": "apple",
  "UIKit": "apple",
  "AppKit": "apple",
  "Combine": "apple",
  "Core Data": "apple",
  "StoreKit 2": "apple",
  "WidgetKit": "apple",
  "Swift Charts": "apple",
  "Mac Catalyst": "apple",
  "Apple IAP": "apple",
  "Sign in with Apple": "apple",
  "Android": "android",
  "Hilt": "android",
  "Room": "android",
  "WorkManager": "android",
  "Jetpack Compose": "jetpackcompose",
  "Material 3": "materialdesign",
  ".NET": "dotnet",
  ".NET 8": "dotnet",
  "WPF": "dotnet",
  "MAUI": "dotnet",
  "Windows": "windows",
  "WinUI 3": "windows",
  "MSIX": "windows",
  "C#": "csharp",
  "Tauri": "tauri",
  "Flutter": "flutter",
  "Qt": "qt",
  "Qt 6": "qt",
  "App Store": "appstore",
  "App Store Connect": "appstore",
  "Mac App Store": "appstore",
  "Google Play": "googleplay",
  "Google Play Console": "googleplay",
  "Google Play Billing": "googleplay",
  "Play Billing": "googleplay",
  "Microsoft Store": "microsoftstore",
  "Fastlane": "fastlane",
  "Xcode": "xcode",
  "Xcode Cloud": "xcode",
  "TypeScript": "typescript",
  "shadcn/ui": "shadcnui",
  "HeroUI": "heroui",
  "Framer Motion": "framer",
  "Drizzle": "drizzle",
  "Prisma": "prisma",
  "Redis": "redis",
  "Cloudflare": "cloudflare",
  "Cloudflare D1": "cloudflare",
  "Cloudflare Pages": "cloudflare",
  "Cloudflare Workers": "cloudflare",
  "Stripe": "stripe",
  "Stripe Billing": "stripe",
  "Stripe Connect": "stripe",
  "RevenueCat": "revenuecat",
  "Clerk": "clerk",
  "Vercel": "vercel",
  "Hostinger VPS": "hostinger",
  "n8n": "n8n",
  "Telegram": "telegram",
  "Telegram Bot API": "telegram",
  "Resend": "resend",
  "Resend / SMTP": "resend",
  "Anthropic": "anthropic",
  "Claude": "claude",
  "Anthropic Claude": "claude",
  "OpenAI": "openai",
  "Google Gemini": "googlegemini",
  "Gemini": "googlegemini",
  "Mistral": "mistralai",
  "Replicate": "replicate",
  "Llama": "meta",
  "Llama 3": "meta",
  "Ollama": "ollama",
  "Make": "make",
  "Make.com": "make",
  "Temporal": "temporal",
  "Bun": "bun",
  "Deno": "deno",
  "Docker": "docker",
  "Hetzner": "hetzner",
  "Hetzner VPS": "hetzner",
  "Railway": "railway",
  "Fly.io": "flydotio",
  "Linux": "linux"
};

export function TechnologyChips({ technologies, label }: { technologies: readonly string[]; label: string }) {
  return (
    <ul className={styles.list} aria-label={label} role="list">
      {technologies.map((technology) => {
        const icon = TECHNOLOGY_ICONS[technology];
        return (
          <li key={technology} className={styles.chip}>
            {icon && (
              <span className={styles.icon} aria-hidden="true"
                style={{ maskImage: `url(/icons/technologies/${icon}.svg)` }} />
            )}
            <bdi>{technology}</bdi>
          </li>
        );
      })}
    </ul>
  );
}
